### PR TITLE
3/fix relationships in arrays

### LINKED ISSUE #2586: 3.0: Relationship type fields cause crashes in case they are part of an array field
PLEASE NOTE: make sure the bug exists in the latest patch level of your major version of Apostrophe. For instance, if you are running a 2.x version of Apostrophe, you should use the latest in that major version to confirm the bug.

## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. Create a new piece type, and add an 'array' field
> 2. Add a 'relationship' type field to the array
> 3. Attempt to add a new piece of this type using the front end

The application crashes with the following error:
````
TypeError: fn is not a function
    at Object._get (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/lib/joinr.js:208:12)
    at Object._has (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/lib/joinr.js:191:20)
    at byArray (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/lib/joinr.js:66:17)
    at Object.relationshipDriver (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/index.js:1520:15)
    at Object.relate (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/index.js:797:21)
    at Object.relate (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/schema/index.js:1750:52)
    at Object.load (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/widget-type/index.js:188:32)
    at Object.after (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/doc-type/index.js:1256:29)
    at Object.after (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/doc-type/index.js:1746:29)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async Object.toArray (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/doc-type/index.js:1494:11)
    at async Object.toObject (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/doc-type/index.js:1456:27)
    at async Object.withLock (/Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/page/index.js:638:18)
    at async /Users/joe/[snip]/node_modules/apostrophe/modules/@apostrophecms/module/index.js:124:30
````

## Details

**Version of Node.js:**
*PLEASE NOTE: Only stable LTS versions (10.x and 12.x) are fully supported but we will do our best with newer versions.*
v15.2.0

**Server Operating System:**
*The server (which might be your dev laptop) on which Apostrophe is running. Linux? MacOS X? Windows? Is Docker involved?*
macOS Big Sur

**Additional context:**
> So far, only fix I found is to manually remove these from the doc, after which the application will start back up again.
> It's worth noting that other field types are working fine, it's only relationship fields which aren't working in arrays.

**Screenshots**
*If applicable, add screenshots to help explain your problem.*

### PR DESCRIPTION
**Pull request by boutell**
Closes #2586 thanks to Joe Innes!

### CODE REVIEW

**Comment by abea** [comment]
It looks like one of our tests may need to be updated.

**Comment by abea** [comment]
```
Error:
undefined undefined, field name _products:

idsStorage property does not match the idsStorage property of any relationship in the schema for product. Hint: you are taking advantage of a relationship already being edited in the schema for that type, your idsStorage must be the same to find the data there.

    at fail (/Users/abea/Apos/apostrophe/modules/@apostrophecms/schema/index.js:378:981)
    at Object.validate (/Users/abea/Apos/apostrophe/modules/@apostrophecms/schema/index.js:80:716)
    at validateField (/Users/abea/Apos/apostrophe/modules/@apostrophecms/schema/index.js:378:836)
    at Array.forEach (<anonymous>)
    at Object.validate (/Users/abea/Apos/apostrophe/modules/@apostrophecms/schema/index.js:377:279)
```

**Review by abea — COMMENTED** [review]
I don't see any obvious issues with the code, but the tests are failing.

**Comment by boutell** [comment]
Actually this was a bug, good job tests! Fixed. Tests pass and you can edit the relationship nested in the array field I added to the global doc in the `3/array-with-relationship` branch of a3-demo.

**Review by abea — APPROVED** [review]

**Pull request merged**
