### PR TITLE
Only add footer height to modal if footer is present

### PR DESCRIPTION
**Pull request by paulisloud**
Previously this method would always undersize the modal by 50px. I believe 50px was a stand-in for footerHeight, so this commit replaces the hardcoded value with the calculated footer height. In my testing, this change does work to:
* Size the window appropriately if there is a footer present in the modal
* Size the window to leave no space for the footer if no footer is present

### CODE REVIEW

**Comment by paulisloud** [comment]
Would it be possible to get a review on this? Fairly trivial change here.

**Comment by stuartromanek** [comment]
sorry about that @paulisloud .. will test this today!

**Comment by stuartromanek** [comment]
thanks @paulisloud !

**Comment by paulisloud** [comment]
Great, thanks @stuartromanek!

**Pull request merged**
