### PR TITLE
Set 301 HTTP status code when redirecting with apostrophe-soft-redirects

### LINKED ISSUE #1352: [apostrophe-soft-redirects] Sending HTTP 301 instead of 302 with changed slugs
Hi there,
although the name of the module `apostrophe-soft-redirect` might suggest otherwise, I believe the better way to redirect user agents with a HTTP 301 instead of the standard HTTP 302 as used by the [`res.redirect`](https://expressjs.com/en/4x/api.html#res.redirect) method in express.js. The change of the URL in Apostrophe is *permanent*. This is also recommended by Google, see https://support.google.com/webmasters/answer/93633?hl=en

> If you need to change the URL of a page as it is shown in search engine results, we recommend that you use a server-side 301 redirect. This is the best way to ensure that users and search engines are directed to the correct page. The 301 status code means that a page has permanently moved to a new location.

The redirect is happening here: https://github.com/apostrophecms/apostrophe/blob/master/lib/modules/apostrophe-soft-redirects/index.js#L45

I'll provide a PR. What do you think?

Thanks for making Apostrophe!
Leo

### PR DESCRIPTION
**Pull request by leomelzer**
Closes #1352

Happy to elaborate or adapt the changes!

### CODE REVIEW

**Comment by boutell** [comment]
Absolutely, but this should be an option, not default behavior.

**Comment by leomelzer** [comment]
@boutell Good idea! Just added an example.

**Comment by boutell** [comment]
One very last thing I swear:

Let's just change it to `statusCode`. That's consistent with Apostrophe's general philosophy of not duplicating stuff that's implicit in the name of the module.

**Comment by leomelzer** [comment]
@boutell Done!

**Comment by boutell** [comment]
This will be in our next release. Thanks for contributing!

**Pull request merged**
