### PR TITLE
fix publish parents

### PR DESCRIPTION
**Pull request by boutell**
New bug never published, so changelog entry not needed.

### CODE REVIEW

**Comment by stuartromanek** [comment]
I got one of these but then was not able to reproduce ..
image

Then I
- Made a fresh draft page and went to it
- made a new page and tried to publish it
It appeared to succeed but the page I was on and published, it's context bar did not reflect this. The page should probably refresh?
Also, this was left in the server console
```POST /api/v1/@apostrophecms/page/cknqduwib000igmswdndmnzch:en:draft/publish:

invalid: invalid
    at Object.error (/Users/sdr/src/apostrophe/modules/@apostrophecms/error/index.js:29:23)
    at Object.ancestorsMustBePublished (/Users/sdr/src/apostrophe/modules/@apostrophecms/page-type/index.js:149:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.emit (/Users/sdr/src/apostrophe/modules/@apostrophecms/module/lib/events.js:40:13)
    at async Object.publish (/Users/sdr/src/apostrophe/modules/@apostrophecms/doc-type/index.js:711:11)
    at async /Users/sdr/src/apostrophe/modules/@apostrophecms/module/index.js:152:30
POST /api/v1/@apostrophecms/page/cko1nvcsc001mlusww1q1rmga:en:draft/publish:

invalid: invalid
    at Object.error (/Users/sdr/src/apostrophe/modules/@apostrophecms/error/index.js:29:23)
    at Object.ancestorsMustBePublished (/Users/sdr/src/apostrophe/modules/@apostrophecms/page-type/index.js:149:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.emit (/Users/sdr/src/apostrophe/modules/@apostrophecms/module/lib/events.js:40:13)
    at async Object.publish (/Users/sdr/src/apostrophe/modules/@apostrophecms/doc-type/index.js:711:11)
    at async /Users/sdr/src/apostrophe/modules/@apostrophecms/module/index.js:152:30
```

**Review by stuartromanek — CHANGES_REQUESTED** [review]
Breakage outlined above

**Comment by boutell** [comment]
I fixed the bugs that caused the wonky dialog boxes and stuff.

As for refreshing the page we're on in this situation, I did introduce more code to refresh the context bar, but being incidentally published in a modal doesn't mean we should switch out of draft edit mode, so I'm not sure what was expected there.

**Comment by stuartromanek** [comment]
better but still getting
```Listening at http://localhost:3000
POST /api/v1/@apostrophecms/page/cko1wupjk000g05swuwqvdh64:en:draft/publish:

invalid: invalid
    at Object.error (/Users/sdr/src/apostrophe/modules/@apostrophecms/error/index.js:29:23)
    at Object.ancestorsMustBePublished (/Users/sdr/src/apostrophe/modules/@apostrophecms/page-type/index.js:151:29)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.emit (/Users/sdr/src/apostrophe/modules/@apostrophecms/module/lib/events.js:40:13)
    at async Object.publish (/Users/sdr/src/apostrophe/modules/@apostrophecms/doc-type/index.js:711:11)
    at async /Users/sdr/src/apostrophe/modules/@apostrophecms/module/index.js:152:30
```
in the console on Publish

**Comment by boutell** [comment]
@stuartromanek that is normal, the REST pattern calls for using HTTP errors to signify things, and our logic reads that and retries. The console should probably be quieter on non-500 errors but that's a different ticket.

**Review by stuartromanek — APPROVED** [review]

**Pull request merged**
