### PR TITLE
do not block page when relationship autocomplete is searching

### PR DESCRIPTION
**Pull request by stuartromanek**
https://apostrophecms.atlassian.net/jira/software/projects/A30U/boards/4

This causing flashing in Safari and is not an intended experience anyway.

requesting Tommy 'lock the page' Boutell for the official blessing

### CODE REVIEW

**Comment by boutell** [comment]
Sure that's fine, but how about some kind of local busy indicator instead then, in case it is slow?

And why do we have any flashing concerns — shouldn't our global busy indicator fade in slow, like it does in A2, so if it's quick you never see it?

**Review by boutell — APPROVED** [review]
Sure that's fine in that there's no huge problem if we don't lock the page for this one. But how about some kind of local busy indicator instead then, in case it is slow?

And why do we have any flashing concerns — shouldn't our global busy indicator fade in slow, like it does in A2, so if it's quick you never see it?

**Comment by boutell** [comment]
Am approving but would like your thoughts on those followup concerns.

**Comment by stuartromanek** [comment]
a local busy indicator would be swell, i can make an issue for that.

To be totally honest I haven't looked at the implementation of our new busy but I've noted it feeling very harsh in other places, I think generally it needs another look

**Pull request merged**
