### PR TITLE
PRO-1229 contributors can delete drafts via the kebab menu

### PR DESCRIPTION
**Pull request by boutell**
No changelog because contribs are new in this release.

### CODE REVIEW

**Review by abea — APPROVED** [review]
Are we calling this the kebab menu?

**Comment by boutell** [comment]
Seems like it

**Comment by stuartromanek** [comment]
_They weren't_

**Comment by abea** [comment]
I guess it is a word people use. https://ux.stackexchange.com/questions/115468/what-the-difference-between-the-2-menu-icons-3-dots-kebab-and-3-lines-hambur

**Comment by stuartromanek** [comment]
it is a modern phrase to describe the icon itself. Context menu is more holistically correct and has been part of OS interface guideline vernacular since the 90s

**Pull request merged**
