### PR TITLE
Draft: link with just a div instead of bubble, demonstrates the bug is resol…

### PR DESCRIPTION
**Pull request by boutell**
…ved, although now you have to click the link icon to dismiss without using ok or cancel

### CODE REVIEW

**Comment by abea** [comment]
In all our discussion I lost track of the problem this is solving. Could you link to that or restate here?

**Comment by boutell** [comment]
* Click on the link button
* Link dialog appears
* Dismiss it via cancel or via clicking elsewhere, ish
* Try to bring up the menu bar bubble menu again
* You can't

**Comment by abea** [comment]
Yep, that looks good. I don't know if this was shot down, but using AposContextMenu seems like a fast way to get this implemented in a fairly nice looking way.

**Review by abea — COMMENTED** [review]
Yep, that looks good. I don't know if this was shot down, but using AposContextMenu seems like a fast way to get this implemented in a fairly nice looking way.

**Comment by stuartromanek** [comment]
Just committed a few UI updates.. the dialog is feeling pretty good.

one last way to break things specific to Link .. if you blur the rich text widget while the link dialog is open both the tiptap editor and link dialog remain on page while the widget itself visually unfocuses.

I can take a look at that tomorrow ..

**Review by stuartromanek — APPROVED** [review]

**Pull request merged**
