### PR TITLE
Changes support email address

### PR DESCRIPTION
**Pull request by abea**

### CODE REVIEW

**Comment by abea** [comment]
We don't have a better one and `support@` should be deprecated for this (we can discuss why offline if you want). `hello@` seems inappropriate for code of conduct violations.

**Comment by boutell** [comment]
I am your G Suite Admin fairy! What is the email address of your dreams and who should receive it? :fairy:

**Comment by boutell** [comment]
(I like the idea of "conduct")

**Comment by abea** [comment]
conduct@apostrophecms.com sounds good. Thanks for your help, Tom. Please let me know when it's ready to put in here.

**Comment by abea** [comment]
Bump

**Pull request merged**
