### PR TITLE
Migration to fix duplicate or missing widget ids

### PR DESCRIPTION
**Pull request by boutell**
. I cannot reproduce the issue from scratch anymore (I tested the migration by manually modifying my database).

But it existed on staging in existing content at one point, so others might have this problem with alpha 1 databases and need this migration to have better success in alpha 2.

I don't see a clear point at which the original bug was fixed though. So if we see it creep back in then I will need to know how to reproduce it. Just using the clone button does not reproduce it.

### CODE REVIEW

**Review by abea — COMMENTED** [review]
What is the benefit of writing migrations into core (that will live forever) if they are motivated by edge cases we create for ourselves in alpha demoing?

**Comment by boutell** [comment]
Because this isn't just for us. We published alpha 1 and people are hopefully evaluating it, and their evaluation of alpha 2 will be brief and disappointing if this bug is currently tormenting them. Thus the migration. We don't want any friction for people migrating from alpha 1 to alpha 2 and if we can fix something they are experiencing we should do that.

However we could later look at moving the pre-release migrations to a command line task that former alpha/beta testers can choose to run, perhaps.

**Comment by abea** [comment]
Yeah, I'd like to see some sign that these aren't permanent. Either moving into a separate thing at some point or being removed at a certain stage.

**Comment by boutell** [comment]
I opened A30U-867 to cover migrating this later. OK to approve?

**Review by abea — APPROVED** [review]

**Pull request merged**
