### PR TITLE
Editor modal area options overflowing

### LINKED ISSUE #3612: Admin modal area options overflowing creating vertical scroll
** Apostrophe version: 2.220.7 **

## To Reproduce

Step by step instructions to reproduce the behavior:

> 1. In any widget configuration menu (admin interface) add an apos area with multiple widgets. (ability to select between 3 widgets to add to the area)
> 2. Click on the + icon to add a widget to the area.
> 3. The dropdown, from which you select a widget, will get cut off at the bottom.
> 4. You have to scroll to see the rest of the options.

## Details

**Version of Node.js:**
*Node v12.18.3*

**Server Operating System:**
*Windows 10, Windows 11, CentOS*

**Additional context:**
> Happens in all major browsers

** Possible Fix **
From poking around I've found a fairly easy fix for this (not sure how it affects the whole interface since I didn't test everything).
In `modal-tabs.less` on line `45` there is style applied as `.apos-schema-group` and the last line is `overflow: auto` (line 50) if I were to disable that style then the issue fixes itself.

**Screenshots**
apos-admin-issue

### PR DESCRIPTION
**Pull request by arthurnagyy**
## Summary

*Summarize the changes briefly, including which issue/ticket this resolves. If it closes an existing Github issue, include "Closes #[issue number]"*

Closes #3612 

## What are the specific steps to test this change?

*For example:*
> 1. Run the website and log in as an admin
> 2. Open a piece manager modal that contains an area with at least 3 elements
> 3. Click on the area to reveal the dropdown
> 4. The dropdowns bottom part isn't cut off anymore and you don't have to scroll to see the bottom options.

## What kind of change does this PR introduce?
*(Check at least one)*

- [X] Bug fix
- [ ] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [X] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [ ] The changelog is updated
- [x] Related documentation has been updated
- [x] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by abea** [comment]
I tested this on a few variations on editor modals and it looks good. @stuartromanek Do you have any concerns about this? I didn't see any previous attempts at this that were rejected.

**Review by abea — CHANGES_REQUESTED** [review]
Please update the Changelog and the PR title to reflect the change.

**Comment by arthurnagyy** [comment]
> Please update the Changelog and the PR title to reflect the change.

Updated both the changelog and package version.

**Comment by abea** [comment]
Thanks. We normally label new changelog sections as "Unreleased" since we often don't know the actual release date and version number until we're actually ready to publish.

**Comment by stuartromanek** [comment]
@abea no concerns from me, testing looks good

**Review by abea — APPROVED** [review]

**Comment by abea** [comment]
@arthurnagyy I think this will be scheduled for release next Wednesday.

**Pull request merged**
