### PR TITLE
Adds pagination to piece manager

### PR DESCRIPTION
**Pull request by abea**
Resolves https://apostrophecms.atlassian.net/browse/A30U-126

### CODE REVIEW

**Comment by abea** [comment]
This is true.

**Comment by abea** [comment]
@boutell You're right. I was worried about a flash of the first page with old filters before it was refreshed with new filters, but that wouldn't happen without calling `getPieces` twice. I'll switch this up.

**Comment by stuartromanek** [comment]
change Menu Swap Icon (up/down arrows in pagination select) size 18

**Comment by stuartromanek** [comment]
image

change spacing rhythm here and add **Page** to the select box, making the UI a consistent series of boxes

**Pull request merged**
