### PR TITLE
PRO-1754 PRO-1857: determine locale via prefix and domain, with tests and necessary surrounding fixes

### PR DESCRIPTION
**Pull request by boutell**

### CODE REVIEW

**Comment by boutell** [comment]
Hitting some complications relating to the consequences of changing the hostname in the URL. Buckle yer somethins.

**Comment by boutell** [comment]
Completes PRO-1857 as a fringe benefit because it eliminates the concern. However I am opening a separate ticket about the need to transfer logins across hostnames when explicitly losing the locale switcher, a stunt we could pull off in 2.x.

**Comment by abea** [comment]
This looks very similar to #3287

**Comment by boutell** [comment]
There's a comment on #3287 saying it shouldn't be reviewed and merged until after this one, which it unavoidably is built upon.

**Comment by boutell** [comment]
Fine with me that you reviewed that one first, but please review this one and we'll sort that first before trying to land all the concerns on the other.

**Pull request closed without merging**
