### PR TITLE
PRO-164 refactor of admin bar, also includes PRO-1002

### PR DESCRIPTION
**Pull request by boutell**
Also the tray (for palette toggle) needs to be styled.

### CODE REVIEW

**Comment by boutell** [comment]
This will also resolve PRO-1002 when complete.

**Comment by stuartromanek** [comment]
Page title no longer shows in context doc bar 

Screen Shot 2021-04-02 at 8 47 34 AM

**Review by stuartromanek — CHANGES_REQUESTED** [review]
context doc title and button styles

**Comment by stuartromanek** [comment]
lot of green and red in this diff, @boutell is there anything I should be looking at extra hard? Noted the surface level differences but if there are more subtle items could you call them out?

**Comment by stuartromanek** [comment]
@boutell when testing this with the assembly boilerplate + palette, there are some strange reactivity cases changing values of palette. Sometimes the Publish Changes button lights up after a change, sometimes not (usually after you've already hit Publish once that page load) .. sometimes it re enables itself seemingly without prompt .. Not sure if you'd consider that bug part of this work

**Comment by boutell** [comment]
I fixed the two bugs you mentioned. I was not able to reproduce a problem with the "publish changes" button so far. I suspect that it would be a preexisting issue, because in general with this refactoring so far, either it works like before or it's just not hooked up at all. Please do open a separate ticket if you can figure out how to reproduce that one.

**Review by stuartromanek — APPROVED** [review]

**Pull request merged**
