### PR TITLE
Make apostrophe-ui button macro render a <button>

### PR DESCRIPTION
**Pull request by fredrikekelund**
As discussed in #1111.

Previously it would render an `<a>`. `<button>`s are generally better suited for this purpose, but above all it solves the problem where `<a>` elements can't be nested.

@stuartromanek, if there are other places that need updating – I'm happy to address those as well!

### CODE REVIEW

**Comment by stuartromanek** [comment]
hey @fredrikekelund we have this on our calendar to review in a few projects that make custom use of the button UI to make sure it is backwards compatible.

Thanks for the PR!

**Comment by fredrikekelund** [comment]
Great! :+1: It's a minor change, but happy to help push it through. Let me know if further changes are needed!

**Comment by abea** [comment]
@fredrikekelund My primary concern would be that it previously used an `href` attribute with `options.url`. A button doesn't know how to use an `href`, so if Apos is using that natively right now it could be a problem. If Apos is using JS to hijack the anchor element behavior right now then this should at least be refactored to a data attribute instead.

That's one thing we'll plan to look at later in the week, but if you have already looked into that please let us know what your thinking was.

**Comment by fredrikekelund** [comment]
@abea @stuartromanek I've updated the macro to be conscious of the `options.url` property! I've also removed the `href` attribute on the `<button>` element, which I overlooked previously. Hopefully it should be all good now!

**Comment by abea** [comment]
Would it be over-engineering to avoid duplication with a conditional for the tag?

```
  {%- if options.url -%}
    {% set tag = 'a' %}
  {%- else -%}
    {% set tag = 'button' %}
  {%- endif -%}

<{{ tag }} {%- if options.url -%}href="{{ options.url }}"{%- endif -%} class="apos-button {{ classes }}" {{ options.attributes }} data-apos-{{ options.action | css }}{% if options.value %}='{{ options.value }}'{% endif %}><span class="apos-button-label">{{ __(label | d('')) }}</span>{% if options.icon %}<i class="fa fa-{{ options.icon }}"></i>{% endif %}</{{tag}}>
```

**Comment by abea** [comment]
I think I prefer less code, but I'll leave that to @stuartromanek to make the call ([I'm a 3 out of 10](http://blog.capwatkins.com/the-sliding-scale-of-giving-a-fuck)). Overall this is a great improvement.

**Comment by stuartromanek** [comment]
I prefer it the way @fredrikekelund has it now. Will get this merged.

Thanks again!

**Pull request merged**
