### PR TITLE
Fix skipping of positional fragment arguments

### PR DESCRIPTION
**Pull request by myovchev**
ref #3056

### CODE REVIEW

**Comment by myovchev** [comment]
@abea Please take a look at the new test cases and confirm I'm reproducing the issue correctly.

**Review by boutell — CHANGES_REQUESTED** [review]
Thanks again Miro! Would you mind adding it to the changelog? 🙏

**Comment by abea** [comment]
that was the case! Thanks, Miro.

**Comment by myovchev** [comment]
@boutell Sorry about that, added to the changelog now :)

**Review by boutell — APPROVED** [review]

**Comment by boutell** [comment]
Merged, thanks again!

**Pull request merged**
