### PR TITLE
Open newly uploaded image in media editor

### PR DESCRIPTION
**Pull request by abea**
Resolves https://apostrophecms.atlassian.net/browse/A30U-425, "As a user, when done uploading a single image in the media manager, I can view and edit image piece properties in the right rail"

To test, upload an image to the media editor. It should open in the right rail editor. Then check a few items and upload an image. The checked items should become un-checked and the new one should be checked and in the editor.

### CODE REVIEW

**Comment by stuartromanek** [comment]
testing this in a3 demo does not do what it advertises

**Review by stuartromanek — CHANGES_REQUESTED** [review]
not working

**Review by stuartromanek — CHANGES_REQUESTED** [review]
If we already have images selected the newly uploaded images should be added to the `selected` array and not reset it

**Comment by abea** [comment]
@stuartromanek Scenario there here says to clear it https://apostrophecms.atlassian.net/browse/A30U-425

> Scenario 3: User uploads new image(s) while currently selecting multiple existing images
> Clear the selected array and pop new items onto it as they are uploaded

**Comment by stuartromanek** [comment]
> @stuartromanek Scenario three here says to clear it https://apostrophecms.atlassian.net/browse/A30U-425
> 
> > Scenario 3: User uploads new image(s) while currently selecting multiple existing images
> > Clear the selected array and pop new items onto it as they are uploaded

Updated scenario 3 to reflect this request ^

I think this direction works for two reasons:
1. You can always jump to Edit for those new images once they're in the Selected rail. The opposite of recovering a selection is not true.
2. If you are mixing select and upload (like in relationships) this preserves your previous work.

**Comment by abea** [comment]
https://media.giphy.com/media/fsnzYr1pgvAQM/giphy.gif

**Review by boutell — APPROVED** [review]

**Review by stuartromanek — APPROVED** [review]

**Pull request merged**
