### PR TITLE
fix story, fix interaction states

### PR DESCRIPTION
**Pull request by stuartromanek**
this got stepped on when moving over from standalone storybook

### CODE REVIEW

**Comment by stuartromanek** [comment]
forgot that this has to be squared with new join work.

@falkodev there is not a standalone join field storybook component .. do the mock apis exist for such a thing? We should have one in storybook

**Comment by abea** [comment]
I don't think we have mock APIs for slats or joins yet.

**Comment by abea** [comment]
@stuartromanek Do you want a review on the draft?

**Comment by abea** [comment]
Removing reviewers until it's ready to go.

**Comment by abea** [comment]
@stuartromanek This can be retired now, right?

**Pull request closed without merging**
