### PR TITLE
Feature/pieces placeholder

### PR DESCRIPTION
**Pull request by abea**
For #1528 (Add a class to apos-pieces-widgets when no matching content )

I tried to use mostly existing UI classes. If there are some that'd make sense for the background and border let me know. We could also move the styles out of the piece widget, but it doesn't seem like that's necessary yet.

screen shot 2018-08-07 at 2 14 18 pm
screen shot 2018-08-07 at 2 14 13 pm

### CODE REVIEW

**Comment by boutell** [comment]
I like the general direction, I would suggest text like "mouse over and click the edit button to select some [label of piece type here]."

**Comment by boutell** [comment]
Bump... any thoughts on my suggestion?

**Comment by abea** [comment]
I think that's a good idea. I'll get an update back up here soon.

**Comment by abea** [comment]
Finally got back to this. I noticed the same problem will persist with the blog widget template. Should I repeat this there?

**Comment by boutell** [comment]
I would imagine this will have little impact on existing sites, because everyone overrides the template, but in future they will hopefully copy it with this nice placeholder as a starting point.

**Pull request merged**
