### PR TITLE
update CKEDITOR

### PR DESCRIPTION
**Pull request by haroun**
## Summary

* Update CKEDITOR to 4.22.1
* Add Font plugin

## What are the specific steps to test this change?

1. Update `sanitizeHtml` options with the following
   ```js
   // lib/modules/apostrophe-rich-text-widgets/index.js
   module.exports = {
     sanitizeHtml: {
       allowedAttributes: {
         a: [ 'href', 'name', 'target' ],
         img: [ 'src', 'srcset', 'alt', 'title', 'width', 'height', 'loading' ],
         span: [ 'style' ]
       }
     }
   };
   ```
2. Add `Font` and `FontSize` to the toolbar
   ```js
   toolbar = [ 'Styles', 'Bold', 'Italic', 'Blockquote', 'Link', 'Anchor', 'Unlink', 'NumberedList', 'BulletedList', 'Split', 'Font', 'FontSize' ];
   ```
3. Edit a rich-text content (adding links, anchors, styles, font and font size, ...). When you save the data and reload the page, the content and style should remain the same.

## What kind of change does this PR introduce?
*(Check at least one)*

- [ ] Bug fix
- [x] New feature
- [ ] Refactor
- [ ] Documentation
- [ ] Build-related changes
- [ ] Other

## Make sure the PR fulfills these requirements:

- [x] It includes a) the existing issue ID being resolved, b) a convincing reason for adding this feature, or c) a clear description of the bug it resolves
- [x] The changelog is updated
- [ ] Related documentation has been updated
- [ ] Related tests have been updated

If adding a new feature without an already open issue, it's best to open a **feature request issue** first and wait for approval before working on it.

**Other information:**

### CODE REVIEW

**Comment by haroun** [comment]
@BoDonkey should we update A2 documentation to tell about the 2 new tools?

**Comment by BoDonkey** [comment]
Yeah - I guess so. Still a lot of legacy users

**Review by ETLaurent — COMMENTED** [review]
Code LGTM but are we OK to add this breaking change? this seems touchy, should not we upgrade ckeditor directly on projects? Just a thought

**Comment by boutell** [comment]
How is this a breaking change? Let's focus on that question. It shouldn't be (same major version of ckeditor).

**Comment by boutell** [comment]
We could also bring in these plugins while sticking to the same version of ckeditor 4 as before.

**Comment by ETLaurent** [comment]
> How is this a breaking change? Let's focus on that question. It shouldn't be (same major version of ckeditor).

@boutell from what I see in the changelog:

> Please update `sanitizeHtml`.`allowedAttributes` with `span` `style`.

**Comment by boutell** [comment]
Yeah A2 doesn't automatically configure sanitizeHtml (and that won't be changing).

But I think that's a requirement we need to document for those who actually choose to enable these features, which are not active by default.

If they didn't have them it doesn't concern them, so not a breaking change if I understand correctly.

**Review by ETLaurent — APPROVED** [review]

**Comment by haroun** [comment]
Handled on project side using https://v2.docs.apostrophecms.org/howtos/ckeditor.html#how-to-add-the-ckeditor-font-plugin

**Comment by haroun** [comment]
Handled on project side using https://v2.docs.apostrophecms.org/howtos/ckeditor.html#how-to-add-the-ckeditor-font-plugin

**Pull request closed without merging**
