### PR TITLE
PRO-2601 simple selectors for QA tests

### PR DESCRIPTION
**Pull request by boutell**
These should allow you to get very close to what you asked for. To avoid pushing props too deeply there are some cases where you'll need a simple descendant selector too. For the username and password fields, use the existing `data-apos-field` selectors as a starting point to reach those fields by name.

### CODE REVIEW

**Comment by boutell** [comment]
With regard to the logout action, you can access that one as `data-apos-test="logout"` after you fire `data-apos-test="authenticatedUserMenuTrigger"`. The name of the logout one is based on the name of the action in apostrophe, again avoiding the need to pass a lot of props for this.

**Review by myovchev — CHANGES_REQUESTED** [review]
Just the context menu item attribute needs a gentle touch. The rest is tested and works as expected.

**Comment by boutell** [comment]
@myovchev I renamed it as requested. Please note that you will still need to use a parent selector (the admin bar one) to guarantee it isn't a context menu item somewhere else that is unrelated to the admin bar and has its own namespace of possible values. Otherwise we would have to do a lot of deep prop pushing just for this to be globally unique. I would prefer the slight awkwardness of a parent selector in the tests to a big change in the structure of the Vue code.

**Review by myovchev — APPROVED** [review]

**Comment by myovchev** [comment]
> @myovchev I renamed it as requested. Please note that you will still need to use a parent selector (the admin bar one) to guarantee it isn't a context menu item somewhere else that is unrelated to the admin bar and has its own namespace of possible values. Otherwise we would have to do a lot of deep prop pushing just for this to be globally unique. I would prefer the slight awkwardness of a parent selector in the tests to a big change in the structure of the Vue code.

I'll keep the `.apos-popover` for the menu items, which is a direct ascendant of `body` and it's outside of the Vue apps. I think Vue uses something called `portals` in ReactJS and the current selector is more than enough, no need of any prop drilling. I'm almost sure the selector you've added alone should be globally unique, as only one popover at a time is written to the DOM, but I'll keep the popover root (it shouldn't be a problem as it is not a presentation class). Additionally, we always match a desired menu item by containing text, so we have double safety.

**Comment by boutell** [comment]
Oh good point, I didn't think of that.

**Pull request merged**
