### PR TITLE
Add hyphens to some keywords

### PR DESCRIPTION
**Pull request by crstnio**
NPM treats a "content management system" as three different keywords in search.

### CODE REVIEW

**Comment by boutell** [comment]
I see your comment about npm treating that as three separate keywords. You're saying npm won't find a space separated keyword at all?

**Comment by crstnio** [comment]
I tested `keywords:content management system` as search and NPM shows only modules with these three keywords.

But I now see that keywords:"content management system" shows exactly that ...

So, it doesn't seem to matter at all. You prefer with spaces, right? I will update all PRs if so.

**Comment by boutell** [comment]
Prefer spaces yes. Thanks!

**Comment by crstnio** [comment]
Sorry for the mess. I updated these PRs. Closing this now. 👍

**Pull request closed without merging**
