### PR TITLE
deleted unnecesary assignation of choices

### PR DESCRIPTION
**Pull request by ecb34**
field.idField always should be empty for a joinByArray

### CODE REVIEW

**Review by abea — COMMENTED** [review]
The more obvious change there would be to use `idsField` instead of `idField`. Can you explain why this isn't needed?

I'm not super familiar with this UI code myself, so I'm looking to understand where this might end up. @boutell Do you have an insight there?

**Comment by ecb34** [comment]
because you set the choices afterwards in the set method, I think that chooser.set([]) can also be removed, but Iḿ not 100% sure
image

**Comment by abea** [comment]
👍 Ah, that looks right. Tagging @boutell for an additional review to be sure.

**Review by boutell — CHANGES_REQUESTED** [review]
The fix is correct, thank you @ecb34! I appreciate you tracking this down.

We should change "assignation" to "assignment." An assignation is something much sneakier 😂 But that is a minor concern.

**Comment by ecb34** [comment]
so chooser.set([]) should be also removed or is necessary for something?

**Comment by boutell** [comment]
Your code is completely correct. Just need to fix the word "assignation" to "assignment" in the changelog. Thanks!

**Review by abea — APPROVED** [review]

**Review by boutell — APPROVED** [review]

**Pull request merged**
