### PR TITLE
Need to wrap text in a paragraph tag when converting to rich text

### PR DESCRIPTION
**Pull request by bgantick**

### CODE REVIEW

**Comment by boutell** [comment]
Is a `p` tag the most likely not to cause problems when it hits ckeditor?

**Comment by bgantick** [comment]
`p` tag is the default I thought?

**Comment by boutell** [comment]
It is yeah. OK.

**Comment by boutell** [comment]
Hmm, I just reverted this because I realized it's a bc break. People may be using this as-is and adding their own wrapper tag. Now they will have two.

Please address by adding an optional second argument, an `options` object with a `wrapper` property that, if present, should be the wrapper tag.

**Pull request merged**
